function P = P(in1)
%P
%    P = P(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    19-Mar-2021 08:57:09

s1 = in1(1,:);
s2 = in1(2,:);
s3 = in1(3,:);
s4 = in1(4,:);
s5 = in1(5,:);
s6 = in1(6,:);
s_t1 = in1(7,:);
s_t2 = in1(8,:);
s_t3 = in1(9,:);
s_t4 = in1(10,:);
s_t5 = in1(11,:);
s_t6 = in1(12,:);
t2 = cos(s3);
t3 = cos(s6);
t4 = sin(s3);
t5 = sin(s6);
t6 = s_t3.^2;
t7 = s_t6.^2;
P = [0.0;-1.0e+1;0.0;0.0;-1.0e+1;0.0;s1.*-1.0e+2-s_t1.*2.0e+1+t2.*5.0e+1-s_t3.*t4.*1.0e+1-(t2.*t6)./2.0;s2.*-1.0e+2-s_t2.*2.0e+1+t4.*5.0e+1+s_t3.*t2.*1.0e+1-(t4.*t6)./2.0;s4.*-1.0e+2-s_t4.*2.0e+1+t2.*1.0e+2+t3.*5.0e+1-s_t3.*t4.*2.0e+1-s_t6.*t5.*1.0e+1-t2.*t6-(t3.*t7)./2.0;s5.*-1.0e+2-s_t5.*2.0e+1+t4.*1.0e+2+t5.*5.0e+1+s_t3.*t2.*2.0e+1+s_t6.*t3.*1.0e+1-t4.*t6-(t5.*t7)./2.0];
